In [1]:
import numpy as np

In [5]:
a = np.random.randn(10)

In [6]:
a

array([-0.24953715, -0.54954617,  1.23990114, -0.8761219 ,  0.86729128,
       -0.36398598,  0.71844641, -0.73366194, -0.07824018, -1.70568204])

In [7]:
exp_a = np.exp(a)

In [8]:
exp_a

array([0.77916133, 0.57721171, 3.45527187, 0.4163946 , 2.38045412,
       0.69490094, 2.05124395, 0.4801475 , 0.92474229, 0.18164845])

In [9]:
result = exp_a / exp_a.sum()

In [10]:
result

array([0.06524996, 0.04833793, 0.28935774, 0.03487048, 0.19934837,
       0.05819367, 0.17177905, 0.0402094 , 0.07744147, 0.01521194])

In [11]:
result.sum()

np.float64(1.0)

In [12]:
A = np.random.randn(100, 5)

In [13]:
A

array([[ 8.64604344e-02, -2.88005742e-01,  1.74085994e+00,
        -5.67736714e-01, -1.47258021e+00],
       [-4.09942020e-01, -1.91509370e-03,  1.94518349e+00,
        -2.08550094e-01,  1.73910758e+00],
       [-1.31930401e+00,  9.51959441e-01,  4.98691949e-01,
        -1.62560591e-01,  3.45334906e-01],
       [-1.08556823e+00,  7.48459201e-01, -5.54347481e-01,
        -3.50088659e-01, -1.10120880e-01],
       [-9.93951336e-01, -7.64420051e-01,  7.54947437e-01,
         9.80030042e-01, -1.35204572e+00],
       [ 2.33786285e+00, -2.91677970e-01,  5.46225602e-02,
         1.42696652e+00, -7.34147087e-01],
       [ 1.24415892e-01,  2.89414545e-01, -6.62452352e-01,
        -8.93497353e-01,  8.06985786e-02],
       [ 1.86785972e+00,  6.89506176e-01, -4.44958142e-01,
        -4.02024278e-01,  1.34160723e+00],
       [ 1.36617690e+00,  1.84286285e-01, -1.05923837e+00,
        -5.19892541e-01, -1.05844430e+00],
       [-3.67797292e-01,  3.57338103e-02, -2.32875160e+00,
        -5.48215236e-01

In [14]:
exp_A = np.exp(A) / np.exp(A).sum(axis=1, keepdims=True)

In [15]:
exp_A

array([[0.1307567 , 0.08991566, 0.68384948, 0.06797508, 0.02750307],
       [0.04377688, 0.06583376, 0.46138434, 0.05354368, 0.37546133],
       [0.0395031 , 0.38284977, 0.24331945, 0.12560256, 0.20872511],
       [0.07299863, 0.45690162, 0.12417122, 0.15231035, 0.19361817],
       [0.06287501, 0.07909741, 0.3614225 , 0.45265499, 0.04395008],
       [0.61631139, 0.04444318, 0.06283499, 0.247858  , 0.02855244],
       [0.25295754, 0.29833598, 0.11516356, 0.09140575, 0.24213716],
       [0.4759851 , 0.14650111, 0.04711393, 0.04918076, 0.2812191 ],
       [0.61150181, 0.18754659, 0.05408207, 0.09274451, 0.05412503],
       [0.26041286, 0.38986456, 0.03664636, 0.21742422, 0.095652  ],
       [0.4530031 , 0.16513422, 0.12038949, 0.09753973, 0.16393346],
       [0.07938155, 0.30605491, 0.19942253, 0.31449132, 0.10064969],
       [0.42468761, 0.12157387, 0.09350188, 0.02456125, 0.33567539],
       [0.19357485, 0.11371297, 0.07834638, 0.12038518, 0.49398061],
       [0.203697  , 0.03314086, 0.

In [16]:
exp_A.sum(axis=1)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [17]:
exp_A.sum(axis=1, keepdims=True).shape

(100, 1)

In [18]:
exp_A.sum(axis=0, keepdims=True)

array([[21.63074307, 19.09262902, 21.53603821, 19.07078369, 18.66980602]])

#### Matrix Addition - Practice

In [19]:
import pandas as pd

W = pd.DataFrame([[23,129,10,85],
              [678,2,99,88],
              [111,89,67,23]])
W

,0,1,2,3
0,23,129,10,85
1,678,2,99,88
2,111,89,67,23


In [159]:
W.shape

(3, 4)

In [160]:
X = pd.DataFrame([[1,2,3,4,],[7,8,9,10],[12,13,14,15]])
X

,0,1,2,3
0,1,2,3,4
1,7,8,9,10
2,12,13,14,15


In [161]:
X.shape

(3, 4)

In [170]:
b = np.array([25,50,39])
b

array([25, 50, 39])

In [171]:
W_T = W.T
W_T.shape

(4, 3)

In [172]:
W_T.dot(X)

,0,1,2,3
0,6101,6913,7725,8537
1,1211,1431,1651,1871
2,1507,1683,1859,2035
3,977,1173,1369,1565


In [173]:
W_T

,0,1,2
0,23,678,111
1,129,2,89
2,10,99,67
3,85,88,23


In [181]:
X.dot(W.T) + b

,0,1,2
0,676,1381,621
1,2158,6583,2361
2,3393,10918,3811
